# This file was generated by GoReleaser. DO NOT EDIT.
class Tickgit < Formula
  desc "Tickets as config"
  homepage "https://augmentable.io/"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/augmentable-dev/tickgit/releases/download/v0.0.4/tickgit_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "1982df29e109a913bf35475676b9f5d420a49a604c85753966dec8c566d5da78"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/augmentable-dev/tickgit/releases/download/v0.0.4/tickgit_0.0.4_Linux_x86_64.tar.gz"
      sha256 "fd0c8c469eca26ec8a55706d2f86b707cca6370bfdb0ada554a28b6af3c7e5ae"
    end
  end

  def install
    bin.install "tickgit"
  end
end
